version: '3.8'
services:
  mysql-container:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodboxdb
    ports:
      - 3307:3306
    restart: always

  springboot-container:
    # Commented out as it's not necessary here
    # build: . ./backend/
    image: Angular-spring-boot:v1
    container_name: springboot_container 
    depends_on:
      - mysql-container  # Corrected service name
    ports:
      - 9090:8080
    restart: always

  angular-container:
    build: ./frontend/
    container_name: angular_container
    ports:
      - 80:80
    restart: always 
