version: '3'
services:
  mysql-container:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodboxdb
    ports:
      - 3307:3306
    restart: always

  springboot-container:
    image: angular-spring-boot:v1
    container_name: springboot_container 
    depends_on:
      - mysql-container
    ports:
      - 9090:8080
    


